name: menv
channels:
  - pytorch
  - sfe1ed40
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.10.18
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - _python_abi3_support=1.0
  - absl-py=2.3.1
  - aiohappyeyeballs=2.6.1
  - aiohttp=3.12.14
  - aiosignal=1.4.0
  - aom=3.6.1
  - asttokens=3.0.0
  - async-timeout=5.0.1
  - attrs=25.3.0
  - aws-c-auth=0.7.22
  - aws-c-cal=0.6.15
  - aws-c-common=0.9.23
  - aws-c-compression=0.2.18
  - aws-c-event-stream=0.4.2
  - aws-c-http=0.8.2
  - aws-c-io=0.14.9
  - aws-c-mqtt=0.10.4
  - aws-c-s3=0.5.10
  - aws-c-sdkutils=0.1.16
  - aws-checksums=0.1.18
  - aws-crt-cpp=0.26.12
  - aws-sdk-cpp=1.11.329
  - azure-core-cpp=1.15.0
  - azure-identity-cpp=1.11.0
  - azure-storage-blobs-cpp=12.13.0
  - azure-storage-common-cpp=12.10.0
  - azure-storage-files-datalake-cpp=12.12.0
  - blas=1.0
  - brotli=1.1.0
  - brotli-bin=1.1.0
  - brotli-python=1.1.0
  - bzip2=1.0.8
  - c-ares=1.34.5
  - ca-certificates=2025.11.12
  - cairo=1.18.0
  - certifi=2025.11.12
  - cffi=1.17.1
  - charset-normalizer=3.4.2
  - click=8.2.1
  - cloudpickle=3.1.1
  - colorama=0.4.6
  - contourpy=1.3.2
  - cpython=3.10.18
  - cuda-cccl_linux-64=12.9.27
  - cuda-cudart=12.1.105
  - cuda-cudart-dev_linux-64=12.9.79
  - cuda-cudart-static_linux-64=12.9.79
  - cuda-cudart_linux-64=12.9.79
  - cuda-cupti=12.1.105
  - cuda-libraries=12.1.0
  - cuda-nvrtc=12.1.105
  - cuda-nvtx=12.1.105
  - cuda-opencl=12.9.19
  - cuda-runtime=12.1.0
  - cuda-version=12.9
  - cupy=13.5.1
  - cupy-core=13.5.1
  - cycler=0.12.1
  - cyrus-sasl=2.1.27
  - datasets=3.6.0
  - datasketch=1.5.9
  - datasketches=5.2.0
  - dbus=1.16.2
  - decorator=5.2.1
  - dill=0.3.8
  - eigen=3.4.0
  - exceptiongroup=1.3.0
  - executing=2.2.1
  - farama-notifications=0.0.4
  - fastrlock=0.8.3
  - ffmpeg=4.2.2
  - filelock=3.18.0
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.15.0
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - fonttools=4.59.1
  - freetype=2.13.3
  - frozenlist=1.7.0
  - fsspec=2025.3.0
  - gevent=25.9.1
  - gflags=2.2.2
  - giflib=5.2.2
  - glib=2.86.0
  - glib-tools=2.86.0
  - glog=0.7.1
  - gmp=6.3.0
  - gmpy2=2.2.1
  - gnutls=3.6.13
  - graphite2=1.3.14
  - greenlet=3.2.4
  - grpcio=1.62.2
  - gst-plugins-base=1.14.1
  - gstreamer=1.14.1
  - gymnasium=1.0.0
  - h2=4.2.0
  - harfbuzz=4.3.0
  - hdf5=1.12.1
  - hf-xet=1.1.5
  - hpack=4.1.0
  - huggingface_hub=0.33.1
  - hyperframe=6.1.0
  - hypothesis=6.136.4
  - icu=73.2
  - idna=3.10
  - importlib-metadata=8.7.0
  - intel-openmp=2022.0.1
  - ipdb=0.13.13
  - ipython=8.37.0
  - jax-jumpy=1.0.0
  - jedi=0.19.2
  - jinja2=3.1.6
  - jiwer=4.0.0
  - joblib=1.5.1
  - jpeg=9e
  - keyutils=1.6.1
  - kiwisolver=1.4.9
  - krb5=1.20.1
  - lame=3.100
  - lcms2=2.15
  - ld_impl_linux-64=2.43
  - lerc=4.0.0
  - libabseil=20240116.2
  - libarrow=16.1.0
  - libarrow-acero=16.1.0
  - libarrow-dataset=16.1.0
  - libarrow-substrait=16.1.0
  - libasprintf=0.24.1
  - libblas=3.9.0
  - libbrotlicommon=1.1.0
  - libbrotlidec=1.1.0
  - libbrotlienc=1.1.0
  - libcblas=3.9.0
  - libclang=14.0.6
  - libclang13=14.0.6
  - libcrc32c=1.1.2
  - libcublas=12.1.0.26
  - libcufft=11.0.2.4
  - libcufile=1.14.1.1
  - libcups=2.3.3
  - libcurand=10.3.10.19
  - libcurl=8.15.0
  - libcusolver=11.4.4.55
  - libcusparse=12.0.2.55
  - libdeflate=1.22
  - libdrm=2.4.125
  - libedit=3.1.20250104
  - libegl=1.7.0
  - libev=4.33
  - libevent=2.1.12
  - libexpat=2.7.0
  - libffi=3.4.6
  - libfreetype=2.13.3
  - libfreetype6=2.13.3
  - libgcc=15.1.0
  - libgcc-ng=15.1.0
  - libgettextpo=0.24.1
  - libgfortran=15.1.0
  - libgfortran-ng=15.1.0
  - libgfortran5=15.1.0
  - libgl=1.7.0
  - libglib=2.86.0
  - libglvnd=1.7.0
  - libglx=1.7.0
  - libgomp=15.1.0
  - libgoogle-cloud=2.25.0
  - libgoogle-cloud-storage=2.25.0
  - libgrpc=1.62.2
  - libiconv=1.18
  - libidn2=2.3.8
  - libjpeg-turbo=2.1.4
  - libkrb5=1.21.3
  - liblapack=3.9.0
  - libllvm14=14.0.6
  - liblzma=5.8.1
  - liblzma-devel=5.8.1
  - libnghttp2=1.64.0
  - libnpp=12.0.2.50
  - libnsl=2.0.1
  - libntlm=1.8
  - libnvjitlink=12.1.105
  - libnvjpeg=12.1.1.14
  - libopentelemetry-cpp=1.16.1
  - libopentelemetry-cpp-headers=1.16.1
  - libopus=1.5.2
  - libparquet=16.1.0
  - libpciaccess=0.18
  - libpng=1.6.49
  - libpq=17.4
  - libprotobuf=4.25.3
  - libre2-11=2023.09.01
  - libsentencepiece=0.2.0
  - libsqlite=3.50.2
  - libssh2=1.11.1
  - libstdcxx=15.1.0
  - libstdcxx-ng=15.1.0
  - libtasn1=4.20.0
  - libthrift=0.19.0
  - libtiff=4.5.1
  - libunistring=0.9.10
  - libutf8proc=2.8.0
  - libuuid=2.38.1
  - libuv=1.51.0
  - libva=2.22.0
  - libvpx=1.7.0
  - libwebp=1.3.2
  - libwebp-base=1.3.2
  - libxcb=1.17.0
  - libxcrypt=4.4.36
  - libxkbcommon=1.11.0
  - libxml2=2.13.8
  - libzlib=1.3.1
  - llvm-openmp=15.0.7
  - lmdb=0.9.31
  - lz4-c=1.9.4
  - markdown=3.8.2
  - markupsafe=3.0.2
  - matplotlib-base=3.10.5
  - matplotlib-inline=0.1.7
  - mkl=2022.1.0
  - mpc=1.3.1
  - mpfr=4.2.1
  - mpmath=1.3.0
  - multidict=6.6.3
  - multiprocess=0.70.16
  - munkres=1.1.4
  - mysql=8.4.0
  - ncurses=6.5
  - nettle=3.6
  - networkx=3.4.2
  - nlohmann_json=3.12.0
  - numpy=1.26.4
  - ocl-icd=2.3.3
  - opencl-headers=2025.06.13
  - opencv=4.10.0
  - openh264=2.1.1
  - openjpeg=2.5.0
  - openldap=2.6.5
  - openssl=3.6.0
  - orc=2.0.1
  - p11-kit=0.24.1
  - packaging=25.0
  - pandas=2.3.1
  - parso=0.8.5
  - patsy=1.0.1
  - pcre2=10.46
  - pexpect=4.9.0
  - pickleshare=0.7.5
  - pillow=11.0.0
  - pip=25.1.1
  - pixman=0.46.4
  - polars=1.33.1
  - polars-default=1.33.1
  - prometheus-cpp=1.2.4
  - prompt-toolkit=3.0.52
  - propcache=0.3.1
  - protobuf=4.25.3
  - psutil=7.1.0
  - pthread-stubs=0.4
  - ptyprocess=0.7.0
  - pure_eval=0.2.3
  - py-cpuinfo=9.0.0
  - pyarrow=16.1.0
  - pyarrow-core=16.1.0
  - pycparser=2.22
  - pyctcdecode=0.5.0
  - pygments=2.19.2
  - pygtrie=2.5.0
  - pyparsing=3.2.3
  - pysocks=1.7.1
  - python=3.10.18
  - python-dateutil=2.9.0.post0
  - python-gil=3.10.18
  - python-tzdata=2025.2
  - python-xxhash=3.5.0
  - python_abi=3.10
  - pytorch=2.5.1
  - pytorch-cuda=12.1
  - pytorch-mutex=1.0
  - pytz=2025.2
  - pyyaml=6.0.2
  - qhull=2020.2
  - qt-main=5.15.2
  - rapidfuzz=3.14.1
  - re2=2023.09.01
  - readline=8.2
  - regex=2024.11.6
  - requests=2.32.4
  - s2n=1.4.16
  - scikit-learn=1.7.0
  - scipy=1.15.2
  - seaborn=0.13.2
  - seaborn-base=0.13.2
  - sentencepiece=0.2.0
  - sentencepiece-python=0.2.0
  - sentencepiece-spm=0.2.0
  - setuptools=80.9.0
  - six=1.17.0
  - snappy=1.2.1
  - sortedcontainers=2.4.0
  - sqlite=3.50.2
  - stable-baselines3=2.7.0
  - stack_data=0.6.3
  - statsmodels=0.14.5
  - svt-av1=1.4.1
  - sympy=1.14.0
  - tensorboard=2.20.0
  - tensorboard-data-server=0.7.0
  - threadpoolctl=3.6.0
  - tiktoken=0.9.0
  - tk=8.6.13
  - tokenizers=0.21.3
  - toml=0.10.2
  - torchaudio=2.5.1
  - torchtriton=3.1.0
  - torchvision=0.20.1
  - tqdm=4.67.1
  - traitlets=5.14.3
  - typing-extensions=4.14.0
  - typing_extensions=4.14.0
  - tzdata=2025b
  - ultralytics=8.3.203
  - unicodedata2=16.0.0
  - unidecode=1.3.8
  - urllib3=2.5.0
  - wayland=1.23.1
  - wayland-protocols=1.45
  - wcwidth=0.2.13
  - websocket=0.2.1
  - werkzeug=3.1.3
  - wheel=0.45.1
  - x264=1!157.20191217
  - x265=3.5
  - xkeyboard-config=2.45
  - xorg-libice=1.1.2
  - xorg-libsm=1.2.6
  - xorg-libx11=1.8.12
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - xorg-libxext=1.3.6
  - xorg-libxfixes=6.0.1
  - xorg-libxrender=0.9.12
  - xxhash=0.8.3
  - xz=5.8.1
  - xz-gpl-tools=5.8.1
  - xz-tools=5.8.1
  - yaml=0.2.5
  - yarl=1.20.1
  - zipp=3.23.0
  - zlib=1.3.1
  - zope.event=6.1
  - zope.interface=8.0.1
  - zstandard=0.23.0
  - zstd=1.5.7
  - pip:
      - anyio==4.10.0
      - h11==0.16.0
      - httpcore==1.0.9
      - httpx==0.28.1
      - nvidia-cublas-cu12==12.9.0.13
      - nvidia-cuda-cccl-cu12==12.9.27
      - nvidia-cuda-cupti-cu12==12.9.19
      - nvidia-cuda-nvrtc-cu12==12.9.41
      - nvidia-cuda-runtime-cu12==12.9.37
      - nvidia-cudnn-cu12==9.9.0.52
      - nvidia-cufft-cu12==11.4.0.6
      - nvidia-cufile-cu12==1.14.0.30
      - nvidia-curand-cu12==10.3.10.19
      - nvidia-cusolver-cu12==11.7.4.40
      - nvidia-cusparse-cu12==12.5.9.5
      - nvidia-cusparselt-cu12==0.7.1
      - nvidia-nccl-cu12==2.27.3
      - nvidia-nvjitlink-cu12==12.9.41
      - nvidia-nvtx-cu12==12.9.19
      - opt-einsum==3.3.0
      - paddlepaddle-gpu==3.2.0
      - safetensors==0.6.2
      - sniffio==1.3.1

